# Generated by Django 3.1.7 on 2021-03-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='recipes/')),
                ('title', models.CharField(max_length=150, null=True)),
                ('published', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], default='Breakfast', max_length=15)),
                ('prep_time', models.IntegerField(null=True)),
                ('cook_time', models.IntegerField(null=True)),
                ('cook_temp', models.IntegerField(null=True)),
                ('degree', models.CharField(choices=[('Fahrenheit', 'Fahrenheit'), ('Celsius', 'Celsius')], default='Fahrenheit', max_length=10)),
                ('yeilds', models.IntegerField(null=True)),
                ('food_type', models.CharField(max_length=50, null=True)),
                ('ingredients', models.JSONField(null=True)),
                ('directions', models.CharField(max_length=600, null=True)),
                ('notes', models.CharField(max_length=250)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
